=== houseelectricsopen/typedpath/typedpath.code/testplugin/src/main/resources/fromjsonschema/schema/referencedata.result.now.json
{
  "$id": "http://example.com/example.json",
  "type": "object",
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "id": {
      "$ref": "#/definitions/uuidPattern"
    },
    "name": {
      "type": "string"
    },
    "templateName": {
      "type": "string"
    },
    "jurisdiction": {
      "type": "string"
    },
    "rank": {
      "type": "integer"
    },
    "text": {
      "type": "string"
    },
    "welshText": {
      "type": "string"
    },
    "urgentTimeLimit": {
      "type": "number"
    },
    "resultDefinitionLinks": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [],
        "properties": {
          "resultDefinitionId": {
            "$ref": "#/definitions/uuidPattern"
          },
          "mandatory": {
            "type": "boolean"
          },
          "primaryResult": {
            "type": "boolean"
          },
          "sequence": {
            "type": "integer"
          }
        }
      }
    }
  }
}

=== houseelectricsopen/typedpath/typedpath.code/testplugin/src/main/resources/fromjsonschema/referencedata.result.now.json
{
  "id": "4daefec6-5f77-4109-82d9-1e60544a6c05",
  "name": "Imprisonment Order",
  "templateName": "Single template",
  "jurisdiction": "B",
  "rank": 1,
  "text": "some text",
  "welshText": "rhywfaint o destun",
  "urgentTimeLimit": 0.5,
  "resultDefinitionLinks": [
    {
      "resultDefinitionId": "0baecac5-222b-402d-9047-84803679edae",
      "mandatory": true,
      "primaryResult": true,
      "sequence": 1
    }
  ]



  }
